apiVersion: v1
kind: Secret
metadata:
  name: pakaura-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "pakaura.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  COHERE_API_KEY: {{ .Values.secrets.cohereApiKey | quote }}
