{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ .Values.global.namespace }}
  labels:
    app: api
    {{- include "pakaura.labels" . | nindent 4 }}
spec:
  selector:
    app: api
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.port }}
      {{- if .Values.api.service.nodePort }}
      nodePort: {{ .Values.api.service.nodePort }}
      {{- end }}
      name: http
  type: {{ .Values.api.service.type }}
{{- end }}
